# Generated by Django 5.2.4 on 2025-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
