# Generated by Django 5.2.4 on 2025-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0003_todo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boatType', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('berth', models.CharField(max_length=20)),
                ('state', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
