# Generated by Django 5.2.4 on 2025-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0004_boat_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='state',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('repair', 'Repair')], default='in', max_length=20),
        ),
    ]
