# Generated by Django 5.2.4 on 2025-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0005_alter_boat_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='boat',
            name='ecod',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boatType',
            field=models.CharField(choices=[('M/Y', 'M/Y'), ('S/Y', 'S/Y'), ('CAT.', 'CAT.'), ('JETSKI', 'JETSKI'), ('TENDER', 'TENDER')], default='M/Y', max_length=30),
        ),
    ]
