# Generated by Django 5.2.4 on 2025-07-29 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0006_boat_cid_boat_ecod_alter_boat_boattype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('boatType', models.CharField(choices=[('M/Y', 'M/Y'), ('S/Y', 'S/Y'), ('CAT.', 'CAT.'), ('JETSKI', 'JETSKI'), ('TENDER', 'TENDER')], default='M/Y', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('trDate', models.DateField()),
                ('trTime', models.TimeField()),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('repair', 'Repair')], default='in', max_length=20)),
                ('passengers', models.IntegerField(blank=True, default='', validators=[django.core.validators.MinValueValidator(1)])),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('edr', models.DateField(blank=True, default='')),
                ('etr', models.TimeField(blank=True, default='')),
                ('trComments', models.CharField(blank=True, default='', max_length=200)),
                ('berth', models.CharField(max_length=20)),
            ],
        ),
    ]
