# Generated by Django 5.2.4 on 2025-08-14 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0007_trafficentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficentry',
            name='edr',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='etr',
            field=models.TimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='passengers',
            field=models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='trComments',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='trDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='trTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
