# Generated by Django 5.2.4 on 2025-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0008_alter_trafficentry_edr_alter_trafficentry_etr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficentry',
            name='trDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='trTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
