# Generated by Django 5.2.4 on 2025-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficApp', '0009_alter_trafficentry_trdate_alter_trafficentry_trtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficentry',
            name='edr',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trafficentry',
            name='trTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
